export const Data = [
  {id: 1, content: 'walk outside'},
  {id: 2, content: 'burger'},
  {id: 3, content: 'salad'},
  {id: 4, content: 'roam'},
  {id: 5, content: 'play'},
  {id: 6, content: 'go outside'},
  {id: 7, content: 'burger'},
  {id: 8, content: 'salad'},
  {id: 9, content: 'roam'},
  {id: 10, content: 'play'},
  {id: 11, content: 'burger'},
  {id: 12, content: 'salad'},
  {id: 13, content: 'roam'},
  {id: 14, content: 'play'},
];
